import type { Metadata } from "next";
import "../globals.css";
import { Footer, Header, Navigation } from "../components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="w-screen min-h-screen bg-white flex flex-col justify-between">
          <div>
            <Header />
            <Navigation />
          </div>
          <main className="text-black">{children}</main>
          <div>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
